version: "3.9"

services:
  db:
    image: postgres:15
    container_name: fra_postgres
    restart: always
    environment:
      POSTGRES_USER: fra_user
      POSTGRES_PASSWORD: fra_password
      POSTGRES_DB: fra_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fra_backend
    restart: always
    depends_on:
      - db
    environment:
      # Example for SQLAlchemy
      DATABASE_URL: postgresql+psycopg2://fra_user:fra_password@db:5432/fra_db
    ports:
      - "8000:8000"
    command: >
      sh -c "
      alembic upgrade head &&
      python -m uvicorn app:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data:
